// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCPMysD_yXKIDJtDUTrbWZdjKv6jiJhmk',
    appId: '1:75334850507:web:97126cd3e6b9682ae6c84e',
    messagingSenderId: '75334850507',
    projectId: 'kodio-app-bdf6a',
    authDomain: 'kodio-app-bdf6a.firebaseapp.com',
    storageBucket: 'kodio-app-bdf6a.firebasestorage.app',
    measurementId: 'G-8L5HVT2KPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSSQ7x1Og5sBYjKOenRKaUjtXMwm9GgpU',
    appId: '1:75334850507:android:38927ff6b44c7922e6c84e',
    messagingSenderId: '75334850507',
    projectId: 'kodio-app-bdf6a',
    storageBucket: 'kodio-app-bdf6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqAkVByuiK3ytP-E9kNJZZnTpKCZwLq4o',
    appId: '1:75334850507:ios:02c82e18acded26be6c84e',
    messagingSenderId: '75334850507',
    projectId: 'kodio-app-bdf6a',
    storageBucket: 'kodio-app-bdf6a.firebasestorage.app',
    iosBundleId: 'com.codio.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqAkVByuiK3ytP-E9kNJZZnTpKCZwLq4o',
    appId: '1:75334850507:ios:02c82e18acded26be6c84e',
    messagingSenderId: '75334850507',
    projectId: 'kodio-app-bdf6a',
    storageBucket: 'kodio-app-bdf6a.firebasestorage.app',
    iosBundleId: 'com.codio.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCPMysD_yXKIDJtDUTrbWZdjKv6jiJhmk',
    appId: '1:75334850507:web:4d884c43881e16c2e6c84e',
    messagingSenderId: '75334850507',
    projectId: 'kodio-app-bdf6a',
    authDomain: 'kodio-app-bdf6a.firebaseapp.com',
    storageBucket: 'kodio-app-bdf6a.firebasestorage.app',
    measurementId: 'G-10HGC8R1S7',
  );
}
